name: "Tag Commit"
author: "Gil Shvarzman"
description: "Triggers on commit and tags it using the following format: `ImageName-Branch-CommitShortSha`"
on: push

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps: 
    - uses: actions/checkout@v1
    - name: Create docker image
      run: ./branch_commit.sh

