version: '3.7'

services:
  # Build the app services
  app:
    build: app
    ports:
      - "5000"
  nginx:
    container_name: nginx_reverse_proxy
    build: nginx_load_balancer
    ports:
      - "9090:9090"
    # Make app as nginx dependency service
    depends_on:
      - app
