name: "Tag Commit"
description: "Triggers on commit and tags the new image it builds using the following format: `ImageName-Branch-CommitShortSha`"
on: push

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Checkout 
    - uses: actions/checkout@v1

    - name: AWS Creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag image
      id:  build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: whist-app
      run: |
        sha=${{ github.sha }}
        branch=${{ github.ref }}
        name="my_app"
        docker image build -t $ECR_REGISTRY/$ECR_REPOSITORY:$name-$branch-$sha -t $ECR_REGISTRY/$ECR_REPOSITORY:lastest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$name-$branch-$sha -t $ECR_REGISTRY/$ECR_REPOSITORY:lastest

